version: '3.8'

services:
  api:
    env_file:
      - .env
    build: .
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql://user:password@db:5432/leetcode_compiler
    ports:
      - "5002:7000"
    depends_on:
      - db
      - redis
    command: python -m src.api.main 

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: leetcode_compiler
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - PYTHONPATH=/app/src
    command: python -u src/api/worker.py
    depends_on:
      - redis
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cpp:
    build:
      context: ./docker/cpp
      dockerfile: Dockerfile
    command: tail -f /dev/null
    depends_on:
      - api

  java:
    build:
      context: ./docker/java
      dockerfile: Dockerfile
    depends_on:
      - api

  node:
    build:
      context: ./docker/nodejs
      dockerfile: Dockerfile
    command: tail -f /dev/null
    depends_on:
      - api

  python:
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    command: tail -f /dev/null
    depends_on:
      - api

volumes:
  db_data:
